# Generated by Django 4.0.4 on 2022-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShorter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('long_url', models.URLField()),
                ('short_url', models.URLField(blank=True, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('url_hash', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-clicks'],
            },
        ),
    ]
