# Generated by Django 4.0.4 on 2022-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_urlshorter_url_hash_urlshorter_url_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshorter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
